### ISSUE TITLE
gedi -e Price -percond flag

### ISSUE THREAD

**Issue by TamaraO** [erhard-lab/price#6]
Hi Florian,

What does `-percond` flag mean for Price pipeline? It appears when I run multiple samples. What are the alternatives? 

`gedi -t /Ribo-seq/Price -e Price -reads /Ribo-seq/Price/./parameters/parameters.cit -genomic  human_g1k_v37 -prefix /Ribo-seq/Price/./parameters/price/parameters -plot -percond -D`

 It's not in the help `gedi -e Price -h`. 

Thank you,

Tamara

**Comment by florianerhard** [comment]
Hi Tamara,

`gedi -e Price -h` only tells you about mandatory parameters, try `gedi -e Price -hh`!

The `-percond` flag makes Price to estimate a codon model for each individual sample instead of a single model for the pooled samples. This should lead to more accurate mapping of reads to codons in most cases, so the pipeline uses that by default.

Florian
